name: CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  all:
    runs-on: ubuntu-latest

    container:
      image: archlinux:multilib-devel

    strategy:
      matrix:
        compiler: [ "gcc", "clang" ]

    steps:
      - name: deps
        run: |
          pacman -Sy
          pacman -S --noconfirm \
            clang \
            cmocka \
            lib32-cmocka \
            cppcheck \
            valgrind

      - uses: actions/checkout@v4

      - name: test
        run: make CC=${{ matrix.compiler }} clean test

      - name: cppcheck
        run: make                      clean cppcheck

#       - name: gcc 32-bit test
#         run: make CC=gcc   MFLAGS=-m32 clean test

#       - name: clang 32-bit test
#         run: make CC=clang MFLAGS=-m32 clean test
