name: CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  all:
    runs-on: ubuntu-latest

    container:
      image: archlinux:multilib-devel

    steps:
      - name: deps
        run: |
          pacman -Sy
          pacman -S --noconfirm \
            clang \
            cmocka \
            lib32-cmocka \
            valgrind

      - uses: actions/checkout@v4

      - name: gcc test
        run: make CC=gcc               clean test

      - name: clang test
        run: make CC=clang             clean test

      - name: cppcheck
        run: make                      clean cppcheck

      - name: gcc 32-bit test
        run: make CC=gcc   MFLAGS=-m32 clean test

      - name: clang 32-bit test
        run: make CC=clang MFLAGS=-m32 clean test
